---
- name: Deploy docker
  hosts: all
  tags: packages
  tasks:
    - name: Install docker install prerequisites
      apt:
        name:
          - ca-certificates
          - curl
        state: latest
        update_cache: yes

    - name: Download docker repo GPG Key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/debian/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'
      become: true

    - name: Add docker's debian repo 
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian bookworm stable"
        state: present
        filename: docker
      when:
        - ansible_distribution == "Devuan"
        - ansible_distribution_release == "daedalus"
        - ansible_architecture == "aarch64"

#   - name: Perform apt update
#     apt:
#       upgrade: yes
#       update_cache: yes

    - name: Install docker components from docker repo
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: yes
      when:
        - ansible_distribution == "Devuan"
        - ansible_distribution_release == "daedalus"
        - ansible_architecture == "aarch64"

# add devuan user to docker group
    - name: Add devuan user to docker group
      ansible.builtin.user:
        name: devuan
        groups: docker

# add new /etc/boot.d/20docker to check that docker is running correctly with dns redirection
#
    - name: Copy new /etc/boot.d/etc-boot.d-20docker
      ansible.builtin.copy:
        src:  templates/etc-boot.d-20docker
        dest: /etc/boot.d/20docker
        owner: root
        group: root
        mode: o+rwx,go+rx
        force: yes

# add new /etc/default/docker
#
    - name: Copy new /etc/default/docker
      ansible.builtin.copy:
        src:  templates/etc-defaults-docker
        dest: /etc/default/docker
        owner: root
        group: root
        mode: o+rw,go+r
        force: yes
      register: docker_default

    - name: Restart dockerd
      service:
        name: docker
        state: restarted
      when: docker_default.changed
